language: erlang
otp_release:
  - 19.2
services:
  - docker
install:
  - make all
script:
  - ./travis.sh test fmke
  - ./rebar3 as test,antidote release
  - ./travis.sh test antidote
  - ./travis.sh bench antidote
cache:
  directories:
  - "$HOME/.cache/rebar3/hex/default"
sudo: required
dist: trusty
