dist: trusty
language: erlang
sudo: false
otp_release:
  - 20.0
  - 19.3
services:
  - docker
install:
  - make all
script:
  - make test
  - make bench
cache:
  directories:
  - "$HOME/.cache/rebar3/hex/default"
