language: erlang
sudo: false
otp_release:
  - 19.3
  - 20.0-rc1
services:
  - docker
install:
  - make all
before_script:
  - kerl list installations
script:
  - ./travis.sh test fmke
  - ./rebar3 as test,antidote release
  - ./travis.sh test antidote
  - ./travis.sh bench antidote
cache:
  directories:
  - "$HOME/.cache/rebar3/hex/default"
sudo: required
dist: trusty
